#!/bin/bash
# Author :Lal Thomas, http://lalamboori.blogspot.com
# License: GPL3, http://www.gnu.org/copyleft/gpl.html
# Credit : Inspired by and based on Mark Wu view add-on. 
# 		   The original one is inspired by and based on Paul Mansfield's projectview, 
#		   http://github.com/the1ts/todo.txt-plugins/blob/master/README.projects


